server:
  port: 8081

spring:
  application:
    name: order-worker
  data:
    mongodb:
      uri: mongodb://localhost:27017/order-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0

rabbitmq:
  order:
    exchange: order.exchange
    queue: order.created.queue
    routing-key: order.created

logging:
  level:
    root: INFO
    olga.ailab: DEBUG
    org.springframework.amqp: INFO
    org.springframework.data.mongodb: INFO 